version: '3.8'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd!
    ports:
      - '1433:1433'

  redis:
    image: redis
    ports:
      - '6379:6379'
